theme: jekyll-theme-minimal
title: Machine Intelligence
description: Personal site of Cosmo Harrigan. 
logo: http://www.machineintelligence.org/cosmo.jpg
show_downloads: false
google_analytics: UA-118401221-1
twitter:
  username: cosmoharrigan
  tweet_count: true              # Show number of shares on Twitter
  size: large
  follow_count: true
footer-links:
  twitter: cosmoharrigan

is_project_page: false
